version: "2"

services:
  vision-sense:
    build: vision-sense
    environment:
        - SERVER_LISTEN_URI=tcp://0.0.0.0:5557
        - DISPLAY=:0
    ports:
        - 5000:5000
    devices:
        - /dev/video0:/dev/video0
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./image-storage:/image-storage

  image-processing:
    build: image-processing
    environment:
      SERVER_CONNECT_URI: tcp://vision-sense:5557
  database:
      build: database
      environment:
          - INFLUXDB_DB=defaultdb
          - INFLUXDB_ADMIN_ENABLED=true
          - INFLUXDB_ADMIN_USER=admin
          - INFLUXDB_ADMIN_PASSWORD=adminpass
          - INFLUXDB_USER=user
          - INFLUXDB_USER_PASSWORD=userpass
      ports:
          - 8086:8086
      volumes:
          - ./database:/var/lib/influxdb
